name: "Dependabot Automerge - Action"

on:
  schedule:
    - cron: '0 0 ? * *'
  workflow_dispatch:

jobs:
  auto-merge:
    name: Auto-merge dependabot updates
    runs-on: ubuntu-latest
    steps:
      - uses: akheron/dependabot-cron-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          auto-merge: major
